#ifndef CONSTANTES_H
#define CONSTANTES_H
#include "bibliotecas.h"

#define LARGURA_TELA    800
#define COLUNA_DISPLAY (LARGURA_TELA - 150)
#define ALTURA_TELA     600
#define LINHA1_DISPLAY  30
#define LABEL_PLAYER    1
#define LABEL_MUNICAO   2
#define LABEL_ZUMBI     3
#define NUM_BALAS       10
#define DURACAO_BALA_1 80
#define NUM_ZUMBIS      70
#define VELOCIDADE_ZUMBI 500.0
#define VELOCIDADE_BALA_1  80.0
#define VELOCIDADE_BALA_2  100.0

#define SCORE_PER_SEC       10
#define SCORE_ZOMBIE_KILL   500
#define SCORE_ZOMBIE_HEADSHOT 2000
#define COMBO_DURATION 3
#define LARGURA_TERRENO 800
#define COMPRIMENTO_TERRENO  800
#define CARTUCHO_PRONTO 1
#define CARTUCHO_CARREGANDO  0
#define CHARGING_TIME  4
#define NUM_TIPOS_ARMA 2
#define ARMA_TIPO_1     0
#define ARMA_TIPO_2     1

#define WAVE_DURATION 60.0
#define WAVE_INTERVAL 10.0
#define WAVE_OFF 0
#define WAVE_ON 1

#define PLAYER_VELOCIDADE_NORMAL 0.8
#define PLAYER_VELOCIDADE_CORRIDA 2.0

#define NUM_SPAWN_POINTS 3

#define HIGHSCORES_CAPACITY 5

#define ZOMBIE_1 1
#define NUM_ARVORES 20

#endif // CONSTANTES_H
